### ISSUE TITLE
Design a logo for RoboHome

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome-Web#103]
Should be useful as a favicon and larger.  Also should contain the source file for creating the logo.

**Comment by EdenSG** [comment]
I can give this a shot!

**Comment by dbudwin** [comment]
Awesome. I'm not a graphics guy so I look forward to whatever you whip up!  Let me know if you have any questions.

**Comment by EdenSG** [comment]
A first shot... Thoughts?
![screen shot 2017-10-02 at 12 47 00 pm](https://user-images.githubusercontent.com/5727389/31089660-f5b59886-a772-11e7-86ca-9825cf4d1a57.png)
![screen shot 2017-10-02 at 1 10 03 pm](https://user-images.githubusercontent.com/5727389/31089720-1d93dce6-a773-11e7-8095-c1ec4a7d2f5a.png)
![screen shot 2017-10-02 at 1 02 54 pm](https://user-images.githubusercontent.com/5727389/31089728-2210219e-a773-11e7-9208-0646fe096f17.png)
![screen shot 2017-10-02 at 1 07 12 pm](https://user-images.githubusercontent.com/5727389/31089727-220ddc04-a773-11e7-9294-353500ce898a.png)

**Comment by dbudwin** [comment]
Definitely looks cool.  Nice and slick.  Love the font too!  How does it look when scaled down to favicon size which I believe is 16x16 px?

What's the symbolism of the 3 dots in the house?  I'm trying to figure out how they convey a sense of automation/control.

Great work :)

**Comment by EdenSG** [comment]
I designed the original at 24x24 ![24x24](https://user-images.githubusercontent.com/5727389/31090319-40d01b28-a775-11e7-856b-117348d8f763.png), but it's easily adaptable to 16x16 ![16x16](https://user-images.githubusercontent.com/5727389/31090336-4d1a2dd8-a775-11e7-8cf5-4739c76a3894.png).

I took inspiration from these kinds of depictions of a robot:
![s233036904537205350_p1_i1_w1200](https://user-images.githubusercontent.com/5727389/31090442-9c490bb8-a775-11e7-8096-a24c17fd5eee.jpeg)
![samsung-unveils-otto-a-personal-assistant-robot-580x330](https://user-images.githubusercontent.com/5727389/31090443-9c4f302e-a775-11e7-85fd-1b4774fa591d.jpg)

The three dots is also a reference to a chat-based interface, which is increasingly the way people think of "bots" — as conversational assistants (à la Siri, Cortana, Google Assistant, etc).

**Comment by dbudwin** [comment]
Makes sense.  I did think they were eyes at first, so that's good.  If you want to make a PR adding the logo we can then make attempts to integrate it into the website in a few locations like the favicon, and on the homepage/header.

**Comment by EdenSG** [comment]
Sure, will do. Do you want versions with the typeface as well?

**Comment by dbudwin** [comment]
Yes please.  I think I prefer the one where the text is to the right.  Also, for the outlined version, how well does that work as a favicon?  I'm trying to imagine in my head if a splash of color (or shades of grey/black) would be beneficial to the logo, or if using the outline version would provide enough "pizzazz" to the logo.

I don't have any images in this project yet and it just occurred to me where should we store them?  I think if we made a new folder at the top level of this project (maybe simply called `images`) to store the source files for the logo and then add the versions of the logo that will actually be used on the site like the favicon to a new folder called `images` [under the `public` folder](https://github.com/dbudwin/RoboHome-Web/tree/master/public).

**Comment by dbudwin** [comment]
Now that #105 is merged, I will close this.  Thanks @EdenSG, you're awesome!

I'll create some issues a little later about adding this logo to the website in some places.
