### ISSUE TITLE
Add support for HHVM to Travis

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome-Web#107]
The `.travis.yml` will need to be modified to include HHVM and any breaking changes will need to be resolved as well.  If for whatever reason it's not possible to support HHVM with a reasonable amount of effort, the reason why should be detailed for future reference.

**Comment by padarom** [comment]
https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0

Laravel lost HHVM support in version 5.3 due to incompatible language features with PHP5.6+

**Comment by dbudwin** [comment]
Gothca, I knew there was a reason I removed HHVM support a while back, but couldn't recall the reasoning.  Now that it's documented that should help keep track of the issue.

**Comment by theofidry** [comment]
I would recommend against it: Laravel dropped support for HHVM. Also HHVM offers very limited benefits over PHP7 if you are not using Hack, has some PHP7 incompatibility and given that Hack is never going to be PHP7 compatible, this is unlikely to go better.

**Comment by dbudwin** [comment]
Sounds good.  I'm going to go ahead and close out this issue then.
