### ISSUE TITLE
Re-add support for Docker back to RoboHome

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome-Web#108]
Before the port to Laravel last year, it used to be possible to use Docker to spin up this project.  This was quite handy for testing purposes and took away some of the necessary effort to configure the project for people new to the project.

The [old docker-compose.yml file](https://github.com/dbudwin/RoboHome-Web/blob/4044f3919549767ae57f3f045b9fecc8d607d7ef/docker-compose.yml) can be used as inspiration for getting this functionality working again.

It should support at the very least:

- PHP 7.1
- MySQL
- phpMyAdmin

When running `docker-compose up` it should be possible to get to a local instance of the RoboHome website.

The crossed out section of the README will need to be un-crossed out, and updated too.

**Comment by metalcamp** [comment]
I would like to take over this issue. :)

**Comment by dbudwin** [comment]
That would be awesome, please let me know how I can help.

**Comment by mkasberg** [comment]
@metalcamp are you still working on this? I got something almost working: https://github.com/mkasberg/RoboHome-Web/commit/1180ae1aad7f2959dabf757591c713fc6dc70f9d

In my setup, the web server is throwing 500s and I don't understand why yet. Does anyone know where the application is configured to log by default, or how I can reconfigure the log destination?

**Comment by dbudwin** [comment]
@mkasberg The application sends logs to `RoboHome-Web/storage/logs/` directory.

I looked at your branch real quick, and I wonder if you could save some effort on creating your own DB schema by running the migrations already in this project by executing `php artisan migrate` command.  See this for more detail: https://laravel.com/docs/5.5/migrations#running-migrations

**Comment by dbudwin** [comment]
Also, if you post the logs here, I may be able to provide some idea as to what's going on.

**Comment by mkasberg** [comment]
OK, I got past several more problems. Still throwing 500s, but for a different reason now. I did switch to `php artisan migrate`; it works well.

Now getting:
```

(1/1)   ErrorException   Object of class Illuminate\Session\SessionManager could not be converted to string
--
in Str.php (line 331)
at HandleExceptions->handleError(4096,  'Object of class Illuminate\\Session\\SessionManager could not be  converted to string',  '/var/www/html/vendor/laravel/framework/src/Illuminate/Support/Str.php',  331, array('search' => '?', 'replace' => object(SessionManager), 'subject' => 'select * from `users` where `user_id` = ? limit 1', 'position' => 40))
```

Maybe it's due to an empty database? I'm stopping here for now but I can play with it some more later.

https://github.com/dbudwin/RoboHome-Web/compare/master...mkasberg:master

**Comment by dbudwin** [comment]
Thanks for the feedback. I'll look into it this afternoon!  The migration should create a suitable database for running the application.

**Comment by dbudwin** [comment]
@mkasberg I was doing some Googling and I was curious if you've used [Laradock](http://laradock.io/) in the past?

It seems promising and like it could be a good way to move forward with this.  It seems fairly straightforward to use if we added it as a submodule to this project.

Thoughts?

**Comment by mkasberg** [comment]
I've never tried it, but it looks cool and might be easy to integrate.

**Comment by dbudwin** [comment]
This has been added in #119
