### ISSUE TITLE
Create 404 error page that matches the site

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome-Web#112]
When a user gets a 404 error by going to a URL that doesn't exist, they should be present with a 404 error page that informs them that the URL doesn't exist and provide a button to go back and a way to get to the home page.  This 404 error page should match the look and feel of the rest of the website.

## Expected Behavior

Going to a non-existent URL will present the user with a helpful 404 error page that tells them it was a 404 error and provides a link to go back to the previous page, and there should also be a link to go to the home page as well.  The 404 error page should match the styling of the rest of the website.  A creative/fun 404 page is also acceptable.

## Current Behavior

Currently when going to non-existent URL, you get the default Laravel error message that says: "Sorry, the page you are looking for could not be found."  There is no good information about what when wrong, or how to go back (besides clicking the back button).

## Possible Solution

Create a 404 error page by using Laravel's supported means for handling HTTP errors: https://laravel.com/docs/5.5/errors#custom-http-error-pages

**Comment by nerdyninja** [comment]
I think no one is assigned, can I take this issue?

**Comment by dbudwin** [comment]
Yes this is fair game. Please let me know if you have any questions. Thanks!

**Comment by nerdyninja** [comment]
#113 I have sent a PR which solves your Error 404 page issue. Have a look. Cheers!

**Comment by einnar82** [comment]
I have sent a PR which solves your issue. Take a look thanks!

**Comment by dbudwin** [comment]
@einnar82 I'm sorry, I don't see any new pull requests.  What PR number is it?

**Comment by kailichiang** [comment]
Is this issue fixed? If not, can you address more about current status and next steps?

In addition, could you give more details about "This 404 error page should match the look and feel of the rest of the website."? It's gonna be helpful!

**Comment by dbudwin** [comment]
No, it is not fixed.  A user attempted to do this last year, but the submission was rejected because it contained a lot of custom modifications to Bootstrap styling.

I would like for the 404 page to look like it belongs with the rest of the website.  For example, it should still use the same instance of Bootstrap and the header you created the other day.  The simplest solution I can imagine is that it should look a lot like the home page before a user logs in, but instead of the "Welcome to RoboHome" message and description, there should be a 404 error message and a link to return to the previous page.

I do want to encourage creativity though.  If you feel like you know of a nice 404 page that matches the look and style of the rest of the website, go for it.  Or post a screenshot of it.
