### ISSUE TITLE
Add confirmation after clicking "Delete" button

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome-Web#152]
## Expected Behavior
When a user wants to delete a device, they click the "Delete" button and the action is completed.  It would be preferable to have a confirmation that asks if they are sure that they want to delete the device.  It should also work well when viewed on a mobile device.

## Current Behavior
The device is immediately deleted when the user clicks the "Delete" button.

![image](https://user-images.githubusercontent.com/15161181/46885017-b3790f00-ce24-11e8-947b-b9c11fb2ed8d.png)

## Possible Solution
It would be acceptable to have a small modal/dialog box appear that says something like "Are you sure you want to delete [insert device name]?" with a "Yes" and a "No" button.  The default selected behavior should be the "No" action so a user doesn't excitedly delete a device.  This also means that pressing the "Enter" button on the keyboard will not have an effect.  It will also be necessary to add a Dusk test case or two to verify this behavior.

**Comment by svichas** [comment]
I will work on it.
