### ISSUE TITLE
Add static fixed footer to bottom of page

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome-Web#153]
## Expected Behavior
Using Bootstrap, a static fixed footer appears at the bottom of each page with a basic copyright notice like "© 2018 by RoboHome."  The word "RoboHome" should be a URL to this repository.  It should also display correctly on a mobile device.  A simple Laravel Dusk test case or two to verify that the footer on the page is present will be useful.

## Current Behavior
Currently there is no footer.

**Comment by MsWebGirl** [comment]
I'd be happy to take this one.

**Comment by dbudwin** [comment]
Awesome, and thank you @MsWebGirl!  Please let me know how I can be of assistance.

**Comment by MsWebGirl** [comment]
I only see one place to change it. (app.blade.php) Is that correct?

**Comment by dbudwin** [comment]
That appears to be the case. Im out and about right now so I can't really double check but this website only has a few different pages like the home screen, login page, sign up page, and the main devices page.

**Comment by dbudwin** [comment]
@MsWebGirl Just wanted to check in and see if you've made any progress with this?

**Comment by MsWebGirl** [comment]
I am still working on this.

**Comment by dbudwin** [comment]
Resolved in #165
