### ISSUE TITLE
Create unit tests for models

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome-Web#17]
It'll be great to have unit tests set up for the models in this project to ensure they persist and retrieve data to the MySQL database correctly.  I've already set up a testing framework per issue #9 which [supports testing databases](https://phpunit.de/manual/current/en/database.html).  If any other additional utilities are needed (like a mocking framework) I'm open to adding them too in their own individual PR.  I recently included the MySQL schema in PR #13 for anyone that may need it.

I think doing a PR per model class is appropriate and I'll gladly support adding the Hacktoberfest label to any of them!

**Comment by mccullagh** [comment]
I can help you with that. I should have a PR tomorrow.

**Comment by dbudwin** [comment]
Awesome @mccullagh!  I appreciate the help.  Let me know if you have any questions or need help with anything.

**Comment by dbudwin** [comment]
PR #29 is currently beginning to address this.

**Comment by dbudwin** [comment]
PR #40 #43 also address this.

**Comment by dbudwin** [comment]
Waiting on this issue to be resolved before I create a model test for `UserDevicesViewModel`: https://github.com/dumblob/mysql2sqlite/issues/14

**Comment by dbudwin** [comment]
Completed in #51
