### ISSUE TITLE
More consistent use of PHP return types

### ISSUE THREAD

**Issue by dbudwin** [dbudwin/RoboHome-Web#93]
Most of them are in place, but it should be added and corrected everywhere to fit this format:

`public funcion myFunction(): void`
`public funcion myFunction(): array`
`public funcion myFunction(): MyType`

**Comment by dbudwin** [comment]
Awesome!  Should be pretty easy :). Mainly just need to add `void` and `array` to the end of some function signatures and take away a space after the name of the function and the colon.  Let me know if you have any questions.

**Comment by michaeltintiuc** [comment]
Regarding the format of return types, since most of the code used `function() : type` format I went with it, there are a lot of occurrences to be replaced throughout the code-base

**Comment by michaeltintiuc** [comment]
Perhaps best if a separate PR was made to address the above issue

**Comment by dbudwin** [comment]
Correct.  The intent was to change the occurrences with the space, to the version without.  The reason being is that it's more consistent with the PHP docs and also it's how PhpStorm generates function names with return types automatically.

I would prefer maybe just a separate commit instead of another PR.

I'm getting ready to merge an already open PR when I finish the review in a minute so a rebase will be needed but luckily the rebase should be pretty straightforward.

**Comment by michaeltintiuc** [comment]
Already made the commit, sure rebase is not a problem

**Comment by dbudwin** [comment]
Completed in #96 and due to the closing of #100.  Thank you @michaeltintiuc.
